export const LOGIN = "LOGIN";
export const INDIVIDU_REGISTER = "INDIVIDU_REGISTER";
export const ORGANISATION_REGISTER = "ORGANISATION_REGISTER";
export const GET_USER = "GET_USER";
export const NO_USER = "NO_USER";
export const LOADING_USER = "LOADING_USER"